name: HerokuContainer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  $HEROKU_API_KEY:  ${{ secrets.HEROKU_API_KEY }}
  $APP_NAME:  ${{ secrets.APP_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      run: |
         docker login --username=_ --password=${{ env.HEROKU_API_KEY }} registry.heroku.com
         heroku container:push web -a ${{ env.APP_NAME }}
         heroku container:release web -a ${{ env.APP_NAME }}
